begin;

-- Some verified reader entries are instruction-only, and the German translation is
-- intentionally blank where no reviewed translation has been supplied. The three
-- fields remain mandatory and at least one component must contain text.
alter table public.religious_text_paragraphs
  drop constraint religious_text_paragraphs_arabic_check,
  drop constraint religious_text_paragraphs_transliteration_check,
  drop constraint religious_text_paragraphs_translation_de_check,
  add constraint religious_text_paragraphs_has_text
    check (
      char_length(btrim(arabic)) > 0
      or char_length(btrim(transliteration)) > 0
      or char_length(btrim(translation_de)) > 0
    );

insert into public.religious_contents (
  id,
  slug,
  title,
  content_type,
  language,
  notes,
  source_references,
  verification_status,
  content_policy,
  reviewed_by,
  reviewed_at,
  version,
  is_published
) values (
  'ziyarat-ashura',
  'ziyarat-ashura',
  'Ziyarat Ashura',
  'ziyarah',
  'Arabisch',
  'Ziyarat Ashura für Imam Hussain (a.). Der geprüfte Text ist absatzweise mit Arabisch, Transliteration und vorhandener deutscher Übersetzung hinterlegt.',
  array['duas-ziyarat-ashura'],
  'verified',
  'approved_for_offline',
  'Projektinhaber',
  '2026-09-14T00:00:00+02:00',
  '1.0.0',
  true
)
on conflict (id) do update
set
  slug = excluded.slug,
  title = excluded.title,
  content_type = excluded.content_type,
  language = excluded.language,
  notes = excluded.notes,
  source_references = excluded.source_references,
  verification_status = excluded.verification_status,
  content_policy = excluded.content_policy,
  reviewed_by = excluded.reviewed_by,
  reviewed_at = excluded.reviewed_at,
  version = excluded.version,
  is_published = excluded.is_published;

delete from public.religious_text_paragraphs
where content_id = 'ziyarat-ashura';

insert into public.religious_text_paragraphs (
  content_id,
  position,
  arabic,
  transliteration,
  translation_de
) values
  ('ziyarat-ashura', 0, 'بِسْمِ اللهِ الرّحْمٰنِ الرّحِیْمِ', 'bismillahi alrrahmani alrraheemi', 'Im Namen Allahs, des Allerbarmers, des Barmherzigen.'),
  ('ziyarat-ashura', 1, 'اَلسَّلاَمُ عَلَيْكَ يَا أَبَا عَبْدِ ٱللَّهِ', 'alssalamu `alayka ya aba `abdillahi', 'Friede sei mit dir, o Abū ʿAbdillāh.'),
  ('ziyarat-ashura', 2, 'اَلسَّلاَمُ عَلَيْكَ يَا بْنَ رَسُولِ ٱللَّهِ', 'alssalamu `alayka yabna rasuli allahi', 'Friede sei mit dir, o Sohn des Gesandten Allahs.'),
  ('ziyarat-ashura', 3, 'السَّلاَمُ عَلَيكَ يَا خِيَرَةِ ٱللَّهِ وَٱبْنَ خَيرَتِهِ', 'alssalamu `alayka ya khiyarata allahi wabna khiyaratihi', 'Friede sei mit dir, o Auserwählter Allahs und Sohn Seines Auserwählten.'),
  ('ziyarat-ashura', 4, 'اَلسَّلاَمُ عَلَيْكَ يَا بْنَ أَمِيرِ ٱلْمُؤْمِنِينَ', 'alssalamu `alayka yabna amiri almu''minina', 'Friede sei mit dir, o Sohn des Fürsten der Gläubigen.'),
  ('ziyarat-ashura', 5, 'وَٱبْنَ سَيِّدِ ٱلْوَصِيِّينَ', 'wabna sayyidi alwasiyyina', ''),
  ('ziyarat-ashura', 6, 'اَلسَّلاَمُ عَلَيْكَ يَا بْنَ فَاطِمَةَ', 'alssalamu `alayka yabna fatimata', ''),
  ('ziyarat-ashura', 7, 'سَيِّدَةِ نِسَاءِ ٱلْعَالَمِينَ', 'sayyidati nisa''i al`alamina', ''),
  ('ziyarat-ashura', 8, 'اَلسَّلاَمُ عَلَيْكَ يَا ثَارَ ٱللَّهِ وَٱبْنَ ثَارِهِ وَٱلْوِتْرَ ٱلْمَوْتُورَ', 'alssalamu `alayka ya thara allahi wabna tharihi walwitra almawtura', ''),
  ('ziyarat-ashura', 9, 'اَلسَّلاَمُ عَلَيْكَ وَعَلَىٰ ٱلأَرْوَاحِ ٱلَّتِي حَلَّتْ بِفِنَائِكَ', 'alssalamu `alayka wa `ala al-arwahi allati hallat bifina''ika', ''),
  ('ziyarat-ashura', 10, 'عَلَيْكُمْ مِنِّي جَمِيعاً سَلاَمُ ٱللَّهِ أَبَداً', '`alaykum minni jami`an salamu allahi abadan', ''),
  ('ziyarat-ashura', 11, 'مَا بَقيتُ وَبَقِيَ ٱللَّيْلُ وَٱلنَّهَارُ', 'ma baqitu wa baqiya allaylu walnnaharu', ''),
  ('ziyarat-ashura', 12, 'يَا أَبَا عَبْدِ ٱللَّهِ', 'ya aba `abdillahi', ''),
  ('ziyarat-ashura', 13, 'لَقَدْ عَظُمَتِ ٱلرَّزِيَّةُ', 'laqad `azumat alrraziyyatu', ''),
  ('ziyarat-ashura', 14, 'وَجَلَّتْ وَعَظُمَتِ ٱلْمُصيبَةُ بِكَ', 'wa jallat wa `azumat almusibatu bika', ''),
  ('ziyarat-ashura', 15, 'عَلَيْنَا وَعَلَىٰ جَمِيعِ أَهْلِ ٱلإِسْلاَمِ', '`alayna wa `ala jami`i ahli al-islami', ''),
  ('ziyarat-ashura', 16, 'وَجَلَّتْ وَعَظُمَتْ مُصيبَتُكَ', 'wa jallat wa `azumat musibatuka', ''),
  ('ziyarat-ashura', 17, 'فِي ٱلسَّمَاوَاتِ عَلَىٰ جَمِيعِ أَهْلِ ٱلسَّمَاوَاتِ', 'fi alssamawati `ala jami`i ahli alssamawati', ''),
  ('ziyarat-ashura', 18, 'فَلَعَنَ ٱللَّهُ أُمَّةً أَسَّسَتْ أَسَاسَ ٱلظُّلْمِ وَٱلْجَوْرِ عَلَيْكُمْ أَهْلَ ٱلْبَيْتِ', 'fala`ana allahu ummatan assasat asasa alzzulmi waljawri `alaykum ahla albayti', ''),
  ('ziyarat-ashura', 19, 'وَلَعَنَ ٱللَّهُ أُمَّةً دَفَعَتْكُمْ عَنْ مَقَامِكُمْ', 'wa la`ana allahu ummatan dafa`atkum `an maqamikum', ''),
  ('ziyarat-ashura', 20, 'وَأَزَالَتْكُمْ عَنْ مَرَاتِبِكُمُ ٱلَّتِي رَتَّبَكُمُ ٱللَّهُ فِيهَا', 'wa azalatkum `an maratibikum allati rattabakum allahu fiha', ''),
  ('ziyarat-ashura', 21, 'وَلَعَنَ ٱللَّهُ أُمَّةً قَتَلَتْكُمْ', 'wa la`ana allahu ummatan qatalatkum', ''),
  ('ziyarat-ashura', 22, 'وَلَعَنَ ٱللَّهُ ٱلْمُمَهِّدِينَ لَهُمْ', 'wa la`ana allahu almumahhidina lahum', ''),
  ('ziyarat-ashura', 23, 'بِٱلتَّمْكِينِ مِنْ قِتَالِكُمْ', 'bilttamkini min qitalikum', ''),
  ('ziyarat-ashura', 24, 'بَرِئْتُ إِلَىٰ ٱللَّهِ وَإِلَيْكُمْ مِنْهُمْ', 'bari''tu ila allahi wa ilaykum minhum', ''),
  ('ziyarat-ashura', 25, 'وَمِنْ أَشْيَاعِهِمْ وَأَتْبَاعِهِمْ وَأَوْلِيَائِهِمْ', 'wa min ashya`ihim wa atba`ihim wa awliya''ihim', ''),
  ('ziyarat-ashura', 26, 'يَا أَبَا عَبْدِ ٱللَّهِ', 'ya aba `abdillahi', ''),
  ('ziyarat-ashura', 27, 'إِنِّي سِلْمٌ لِمَنْ سَالَمَكُمْ', 'inni silmun liman salamakum', ''),
  ('ziyarat-ashura', 28, 'وَحَرْبٌ لِمَنْ حَارَبَكُمْ إِلَىٰ يَوْمِ ٱلْقِيَامَةِ', 'wa harbun liman harabakum ila yawmi alqiyamati', ''),
  ('ziyarat-ashura', 29, 'وَلَعَنَ ٱللَّهُ آلَ زِيَادٍ وَآلَ مَرْوَانَ', 'wa la`ana allahu ala ziyadin wa ala marwana', ''),
  ('ziyarat-ashura', 30, 'وَلَعَنَ ٱللَّهُ بَنِي أُمَيَّةَ قَاطِبَةً', 'wa la`ana allahu bani umayyata qatibatan', ''),
  ('ziyarat-ashura', 31, 'وَلَعَنَ ٱللَّهُ ٱبْنَ مَرْجَانَةَ', 'wa la`ana allahu ibna marjanata', ''),
  ('ziyarat-ashura', 32, 'وَلَعَنَ ٱللَّهُ عُمَرَ بْنَ سَعْدٍ', 'wa la`ana allahu `umara bna sa`din', ''),
  ('ziyarat-ashura', 33, 'وَلَعَنَ ٱللَّهُ شِمْراً', 'wa la`ana allahu shimran', ''),
  ('ziyarat-ashura', 34, 'وَلَعَنَ ٱللَّهُ أُمَّةً أَسْرَجَتْ وَأَلْجَمَتْ', 'wa la`ana allahu ummatan asrajat wa aljamat', ''),
  ('ziyarat-ashura', 35, 'وَتَنَقَّبَتْ لِقِتَالِكَ', 'wa tanaqqabat liqitalika', ''),
  ('ziyarat-ashura', 36, 'بِأَبِي أَنْتَ وَأُمِّي', 'bi''abi anta wa ummi', ''),
  ('ziyarat-ashura', 37, 'لَقَدْ عَظُمَ مُصَابِي بِكَ', 'laqad `azuma musabi bika', ''),
  ('ziyarat-ashura', 38, 'فَأَسْأَلُ ٱللَّهَ ٱلَّذِي أَكْرَمَ مَقَامَكَ وَأَكْرَمَنِي بِكَ', 'fa''as''alu allaha alladhi akrama maqamaka wa akramani bika', ''),
  ('ziyarat-ashura', 39, 'أَنْ يَرْزُقَنِي طَلَبَ ثَأْرِكَ', 'an yarzuqani talaba tha''rika', ''),
  ('ziyarat-ashura', 40, 'مَعَ إِمَامٍ مَنْصُورٍ مِنْ أَهْلِ بَيْتِ مُحَمَّدٍ', 'ma`a imamin mansurin min ahli bayti muhammadin', ''),
  ('ziyarat-ashura', 41, 'صَلَّىٰ ٱللَّهُ عَلَيْهِ وَآلِهِ', 'salla allahu `alayhi wa alihi', ''),
  ('ziyarat-ashura', 42, 'اَللَّهُمَّ ٱجْعَلْنِي عِنْدَكَ وَجِيهاً', 'allahumma ij`alni `indaka wajihan', ''),
  ('ziyarat-ashura', 43, 'بِٱلْحُسَيْنِ عَلَيْهِ ٱلسَّلاَمُ فِي ٱلدُّنْيَا وَٱلآخِرَةِ', 'bilhusayni `alayhi alssalamu fi alddunya wal-akhirati', ''),
  ('ziyarat-ashura', 44, 'يَا أَبَا عَبْدِ ٱللَّهِ', 'ya aba `abdillahi', ''),
  ('ziyarat-ashura', 45, 'إِنِّي أَتَقَرَّبُ إِلَىٰ ٱللَّهِ وَإِلَىٰ رَسُولِهِ', 'inni ataqarrabu ila allahi wa ila rasulihi', ''),
  ('ziyarat-ashura', 46, 'وَإِلَىٰ أَمِيرِ ٱلْمُؤْمِنِينَ وَإِلَىٰ فَاطِمَةَ', 'wa ila amiri almu''minina wa ila fatimata', ''),
  ('ziyarat-ashura', 47, 'وَإِلَىٰ ٱلْحَسَنِ وَإِلَيْكَ بِمُوَالاَتِكَ', 'wa ila alhasani wa ilayka bimuwalatika', ''),
  ('ziyarat-ashura', 48, 'وَبِٱلْبَرَاءَةِ (مِمَّنْ قَاتَلَكَ', 'wa bilbara''ati (mimman qatalaka', ''),
  ('ziyarat-ashura', 49, 'وَنَصَبَ لَكَ ٱلْحَرْبَ', 'wa nasaba laka alharba', ''),
  ('ziyarat-ashura', 50, 'وَبِٱلْبَرَاءَةِ مِمَّنْ أَسَّسَ أَسَاسَ ٱلظُّلْمِ وَٱلْجَوْرِ عَلَيْكُمْ', 'wa bilbara''ati mimman assasa asasa alzzulmi waljawri `alaykum', ''),
  ('ziyarat-ashura', 51, 'وَأَبْرَأُ إِلَىٰ ٱللَّهِ وَإِلَىٰ رَسُولِهِ)', 'wa abra''u ila allahi wa ila rasulihi)', ''),
  ('ziyarat-ashura', 52, 'مِمَّنْ أَسَّسَ أَسَاسَ ذٰلِكَ', 'mimman assasa asasa dhalika', ''),
  ('ziyarat-ashura', 53, 'وَبَنَىٰ عَلَيْهِ بُنْيَانَهُ', 'wa bana `alayhi bunyanahu', ''),
  ('ziyarat-ashura', 54, 'وَجَرَىٰ فِي ظُلْمِهِ وَجَوْرِهِ عَلَيْكُمْ وَعلىٰ أَشْيَاعِكُمْ', 'wa jara fi zulmihi wa jawrihi `alaykum wa `ala ashya`ikum', ''),
  ('ziyarat-ashura', 55, 'بَرِئْتُ إِلَىٰ ٱللَّهِ وَإِلَيْكُمْ مِنْهُمْ', 'bari''tu ila allahi wa ilaykum minhum', ''),
  ('ziyarat-ashura', 56, 'وَأَتَقَرَّبُ إِلَىٰ ٱللَّهِ ثُمَّ إِلَيْكُمْ', 'wa ataqarrabu ila allahi thumma ilaykum', ''),
  ('ziyarat-ashura', 57, 'بِمُوَالاَتِكُمْ وَمُوَالاَةِ وَلِيِّكُمْ', 'bimuwalatikum wa muwalati waliyyikum', ''),
  ('ziyarat-ashura', 58, 'وَبِٱلْبَرَاءَةِ مِنْ أَعْدَائِكُمْ', 'wa bilbara''ati min a`da''ikum', ''),
  ('ziyarat-ashura', 59, 'وَٱلنَّاصِبِينَ لَكُمُ ٱلْحَرْبَ', 'walnnasibina lakum alharba', ''),
  ('ziyarat-ashura', 60, 'وَبِٱلْبَرَاءَةِ مِنْ أَشْيَاعِهِمْ وَأَتْبَاعِهِمْ', 'wa bilbara''ati min ashya`ihim wa atba`ihim', ''),
  ('ziyarat-ashura', 61, 'إِنِّي سِلْمٌ لِمَنْ سَالَمَكُمْ', 'inni silmun liman salamakum', ''),
  ('ziyarat-ashura', 62, 'وَحَرْبٌ لِمَنْ حَارَبَكُمْ', 'wa harbun liman harabakum', ''),
  ('ziyarat-ashura', 63, 'وَوَلِيٌّ لِمَنْ وَالاَكُمْ', 'wa waliyyun liman walakum', ''),
  ('ziyarat-ashura', 64, 'وَعَدُوٌّ لِمَنْ عَادَاكُمْ', 'wa `aduwwun liman `adakum', ''),
  ('ziyarat-ashura', 65, 'فَأَسْأَلُ ٱللَّهَ ٱلَّذِي أَكْرَمَنِي بِمَعْرِفَتِكُمْ', 'fa''as''alu allaha alladhi akramani bima`rifatikum', ''),
  ('ziyarat-ashura', 66, 'وَمَعْرِفَةِ أَوْلِيَائِكُمْ', 'wa ma`rifati awliya''ikum', ''),
  ('ziyarat-ashura', 67, 'وَرَزَقَنِيَ ٱلْبَرَاءَةَ مِنْ أَعْدَائِكُمْ', 'wa razaqani albara''ata min a`da''ikum', ''),
  ('ziyarat-ashura', 68, 'أَنْ يَجْعَلَنِي مَعَكُمْ فِي ٱلدُّنْيَا وَٱلآخِرَةِ', 'an yaj`alani ma`akum fi alddunya wal-akhirati', ''),
  ('ziyarat-ashura', 69, 'وَأَنْ يُثَبِّتَ لِي عِنْدَكُمْ قَدَمَ صِدْقٍ', 'wa an yuthabbita li `indakum qadama sidqin', ''),
  ('ziyarat-ashura', 70, 'فِي ٱلدُّنْيَا وَٱلآخِرَةِ', 'fi alddunya wal-akhirati', ''),
  ('ziyarat-ashura', 71, 'وَأَسْأَلُهُ أَنْ يُبَلِّغَنِيَ ٱلْمَقَامَ ٱلْمَحْمُودَ لَكُمْ عِنْدَ ٱللَّهِ', 'wa as''aluhu an yuballighani almaqama almahmuda lakum `inda allahi', ''),
  ('ziyarat-ashura', 72, 'وَأَنْ يَرْزُقَنِي طَلَبَ ثَأْرِي', 'wa an yarzuqani talaba tha''ri', ''),
  ('ziyarat-ashura', 73, 'مَعَ إِمَامِ هُدىًٰ ظَاهِرٍ', 'ma`a imami hudan zahirin', ''),
  ('ziyarat-ashura', 74, 'نَاطِقٍ بِٱلْحَقِّ مِنْكُمْ', 'natiqin bilhaqqi minkum', ''),
  ('ziyarat-ashura', 75, 'وَأَسْأَلُ ٱللَّهَ بِحَقِّكُمْ', 'wa as''alu allaha bihaqqikum', ''),
  ('ziyarat-ashura', 76, 'وَبِٱلشَّأْنِ ٱلَّذِي لَكُمْ عِنْدَهُ', 'wa bilshsha''ni alladhi lakum `indahu', ''),
  ('ziyarat-ashura', 77, 'أَنْ يُعْطِيَنِي بِمُصَابِي بِكُمْ', 'an yu`tiyani bimusabi bikum', ''),
  ('ziyarat-ashura', 78, 'أَفْضَلَ مَا يُعْطِي مُصَاباً بِمُصِيبَتِهِ', 'afdala ma yu`ti musaban bimusibatihi', ''),
  ('ziyarat-ashura', 79, 'مُصِيبَةً مَا أَعْظَمَهَا', 'musibatan ma a`zamaha', ''),
  ('ziyarat-ashura', 80, 'وَأَعْظَمَ رَزِيَّتَهَا فِي ٱلإِسْلاَمِ', 'wa a`zama raziyyataha fi al-islami', ''),
  ('ziyarat-ashura', 81, 'وَفِي جَمِيعِ ٱلسَّمَاوَاتِ وَٱلأَرْضِ', 'wa fi jami`i alssamawati wal-ardi', ''),
  ('ziyarat-ashura', 82, 'اَللَّهُمَّ ٱجْعَلْنِي فِي مَقَامِي هٰذَا', 'allahumma ij`alni fi maqami hadha', ''),
  ('ziyarat-ashura', 83, 'مِمَّنْ تَنَالُهُ مِنْكَ صَلَوَاتٌ وَرَحْمَةٌ وَمَغْفِرَةٌ', 'mimman tanaluhu minka salawatun wa rahmatun wa maghfiratun', ''),
  ('ziyarat-ashura', 84, 'اَللَّهُمَّ ٱجْعَلْ مَحْيَايَ مَحْيَا مُحَمَّدٍ وَآلِ مُحَمَّدٍ', 'allahumma ij`al mahyaya mahya muhammadin wa ali muhammadin', ''),
  ('ziyarat-ashura', 85, 'وَمَمَاتِي مَمَاتَ مُحَمَّدٍ وَآلِ مُحَمَّدٍ', 'wa mamati mamata muhammadin wa ali muhammadin', ''),
  ('ziyarat-ashura', 86, 'اَللَّهُمَّ إِنَّ هٰذَا يَوْمٌ', 'allahumma inna hadha yawmun', ''),
  ('ziyarat-ashura', 87, 'تَبَرَّكَتْ بِهِ بَنُو أُمَيَّةَ', 'tabarrakat bihi banu umayyata', ''),
  ('ziyarat-ashura', 88, 'وَٱبْنُ آكِلَةِ ٱلأَكبَادِ', 'wabnu akilati al-akbadi', ''),
  ('ziyarat-ashura', 89, 'ٱللَّعِينُ ٱبْنُ ٱللَّعِينِ', 'alla`inu ibnu alla`ini', ''),
  ('ziyarat-ashura', 90, 'عَلَىٰ لِسَانِكَ وَلِسَانِ نَبِيِّكَ', '`ala lisanika wa lisani nabiyyika', ''),
  ('ziyarat-ashura', 91, 'صَلَّىٰ ٱللَّهُ عَلَيْهِ وَآلِهِ', 'salla allahu `alayhi wa alihi', ''),
  ('ziyarat-ashura', 92, 'فِي كُلِّ مَوْطِنٍ وَمَوْقِفٍ', 'fi kulli mawtinin wa mawqifin', ''),
  ('ziyarat-ashura', 93, 'وَقَفَ فِيهِ نَبِيُّكَ صَلَّىٰ ٱللَّهُ عَلَيْهِ وَآلِهِ', 'waqafa fihi nabiyyuka salla allahu `alayhi wa alihi', ''),
  ('ziyarat-ashura', 94, 'اَللَّهُمَّ ٱلْعَنْ أَبَا سُفْيَانَ وَمُعَاوِيَةَ وَيَزيدَ بْنَ مُعَاوِيَةَ', 'allahumma il`an aba sufyana wa mu`awiyata wa yazida bna mu`awiyata', ''),
  ('ziyarat-ashura', 95, 'عَلَيْهِمْ مِنْكَ ٱللَّعْنَةُ أَبَدَ ٱلآبِدِينَ', '`alayhim minka alla`natu abada al-abidina', ''),
  ('ziyarat-ashura', 96, 'وَهٰذَا يَوْمٌ فَرِحَتْ بِهِ آلُ زِيَادٍ وَآلُ مَرْوَانَ', 'wa hadha yawmun farihat bihi alu ziyadin wa alu marwana', ''),
  ('ziyarat-ashura', 97, 'بِقَتْلِهِمُ ٱلْحُسَيْنَ صَلَوَاتُ ٱللَّهِ عَلَيْهِ', 'biqatlihim alhusayna salawatu allahi `alayhi', ''),
  ('ziyarat-ashura', 98, 'اَللَّهُمَّ فَضَاعِفْ عَلَيْهِمُ ٱللَّعْنَ مِنْكَ', 'allahumma fada`if `alayhim alla`na minka', ''),
  ('ziyarat-ashura', 99, 'وَٱلْعَذَابَ (ٱلأَلِيمَ)', 'wal`adhaba (al-alima)', ''),
  ('ziyarat-ashura', 100, 'اَللَّهُمَّ إِنِّي أَتَقَرَّبُ إِلَيْكَ فِي هٰذَا ٱلْيَوْمِ', 'allahumma inni ataqarrabu ilayka fi hadha alyawmi', ''),
  ('ziyarat-ashura', 101, 'وَفِي مَوْقِفِي هٰذَا', 'wa fi mawqifi hadha', ''),
  ('ziyarat-ashura', 102, 'وَأَيَّامِ حَيَاتِي', 'wa ayyami hayati', ''),
  ('ziyarat-ashura', 103, 'بِٱلْبَرَاءَةِ مِنْهُمْ وَٱللَّعْنَةِ عَلَيْهِمْ', 'bilbara''ati minhum walla`nati `alayhim', ''),
  ('ziyarat-ashura', 104, 'وَبِٱلْمُوَالاَةِ لِنَبِيِّكَ وَآلِ نَبِيِّكَ', 'wa bilmuwalati linabiyyika wa ali nabiyyika', ''),
  ('ziyarat-ashura', 105, 'عَلَيْهِ وَعَلَيْهِمُ ٱلسَّلاَمُ', '`alayhi wa `alayhim alssalamu', ''),
  ('ziyarat-ashura', 106, '', '', 'Dann kann die folgende Laʿn hundertmal (oder einmal) wiederholt werden:'),
  ('ziyarat-ashura', 107, 'اَللَّهُمَّ ٱلْعَنْ أَوَّلَ ظَالِمٍ', 'allahumma il`an awwala zalimin', ''),
  ('ziyarat-ashura', 108, 'ظَلَمَ حَقَّ مُحَمَّدٍ وَآلِ مُحَمَّدٍ', 'zalama haqqa muhammadin wa ali muhammadin', ''),
  ('ziyarat-ashura', 109, 'وَآخِرَ تَابِعٍ لَهُ عَلَىٰ ذٰلِكَ', 'wa akhira tabi`in lahu `ala dhalika', ''),
  ('ziyarat-ashura', 110, 'اَللَّهُمَّ ٱلْعَنِ ٱلْعِصَابَةَ ٱلَّتِي جَاهَدَتِ ٱلْحُسَيْنَ', 'allahumma il`an al`isabata allati jahadat alhusayna', ''),
  ('ziyarat-ashura', 111, 'وَشَايَعَتْ وَبَايَعَتْ وَتَابَعَتْ عَلَىٰ قَتْلِهِ', 'wa shaya`at wa baya`at wa taba`at `ala qatlihi', ''),
  ('ziyarat-ashura', 112, 'اَللَّهُمَّ ٱلْعَنْهُمْ جَمِيعاً', 'allahumma il`anhum jami`an', ''),
  ('ziyarat-ashura', 113, '', '', 'Dann kann der folgende Salam hundertmal (oder einmal) wiederholt werden:'),
  ('ziyarat-ashura', 114, 'اَلسَّلاَمُ عَلَيْكَ يَا أَبَا عَبْدِ ٱللَّهِ', 'alssalamu `alayka ya aba `abdillahi', ''),
  ('ziyarat-ashura', 115, 'وَعَلَىٰ ٱلأَرْوَاحِ ٱلَّتِي حَلَّتْ بِفِنَائِكَ', 'wa `ala al-arwahi allati hallat bifina''ika', ''),
  ('ziyarat-ashura', 116, 'عَلَيْكَ مِنِّي سَلاَمُ ٱللَّهِ أَبَداً', '`alayka minni salamu allahi abadan', ''),
  ('ziyarat-ashura', 117, 'مَا بَقيتُ وَبَقِيَ ٱللَّيْلُ وَٱلنَّهَارُ', 'ma baqitu wa baqiya allaylu walnnaharu', ''),
  ('ziyarat-ashura', 118, 'وَلاَ جَعَلَهُ ٱللَّهُ آخِرَ ٱلْعَهْدِ مِنِّي لِزِيَارَتِكُمْ', 'wa la ja`alahu allahu akhira al`ahdi minni liziyaratikum', ''),
  ('ziyarat-ashura', 119, 'اَلسَّلاَمُ عَلَىٰ ٱلْحُسَيْنِ', 'alssalamu `ala alhusayni', ''),
  ('ziyarat-ashura', 120, 'وَعَلَىٰ عَلِيِّ بْنِ ٱلْحُسَيْنِ', 'wa `ala `aliyyi bni alhusayni', ''),
  ('ziyarat-ashura', 121, 'وَعَلَىٰ أَوْلاَدِ ٱلْحُسَيْنِ', 'wa `ala awladi alhusayni', ''),
  ('ziyarat-ashura', 122, 'وَعَلَىٰ أَصْحَابِ ٱلْحُسَيْنِ', 'wa `ala ashabi alhusayni', ''),
  ('ziyarat-ashura', 123, '', '', 'Dann kann Folgendes gesagt werden:'),
  ('ziyarat-ashura', 124, 'اَللَّهُمَّ خُصَّ أَنْتَ أَوَّلَ ظَالِمٍ بِٱللَّعْنِ مِنِّي', 'allahumma khussa anta awwala zalimin billa`ni minni', ''),
  ('ziyarat-ashura', 125, 'وَٱبْدَأْ بِهِ أَوَّلًا', 'wabda'' bihi awwalan', ''),
  ('ziyarat-ashura', 126, 'ثُمَّ ٱلْعَنِ ٱلثَّانِيَ وَٱلثَّالِثَ وَٱلرَّابِعَ', 'thumma il`an alththaniya walththalitha walrrabi`a', ''),
  ('ziyarat-ashura', 127, 'اَللَّهُمَّ ٱلْعَنْ يَزِيدَ خَامِساً', 'allahumma il`an yazida khamisan', ''),
  ('ziyarat-ashura', 128, 'وَٱلْعَنْ عُبَيْدَ ٱللَّهِ بْنَ زِيَادٍ وَٱبْنَ مَرْجَانَةَ', 'wal`an `ubaydallahi bna ziyadin wabna marjanata', ''),
  ('ziyarat-ashura', 129, 'وَعُمَرَ بْنَ سَعْدٍ وَشِمْراً', 'wa `umara bna sa`din wa shimran', ''),
  ('ziyarat-ashura', 130, 'وَآلَ أَبِي سُفْيَانَ وَآلَ زِيَادٍ وَآلَ مَرْوَانَ', 'wa ala abi sufyana wa ala ziyadin wa ala marwana', ''),
  ('ziyarat-ashura', 131, 'إِلَىٰ يَوْمِ ٱلْقِيَامَةِ', 'ila yawmi alqiyamati', ''),
  ('ziyarat-ashura', 132, '', '', 'Dann kann man sich niederwerfen und Folgendes sagen:'),
  ('ziyarat-ashura', 133, 'اَللَّهُمَّ لَكَ ٱلْحَمْدُ', 'allahumma laka alhamdu', ''),
  ('ziyarat-ashura', 134, 'حَمْدَ ٱلشَّاكِرِينَ لَكَ عَلَىٰ مُصَابِهِمْ', 'hamda alshshakirina laka `ala musabihim', ''),
  ('ziyarat-ashura', 135, 'اَلْحَمْدُ لِلَّهِ عَلَىٰ عَظِيمِ رَزِيَّتِي', 'alhamdu lillahi `ala `azimi raziyyati', ''),
  ('ziyarat-ashura', 136, 'اَللَّهُمَّ ٱرْزُقْنِي شَفَاعَةَ ٱلْحُسَيْنِ يَوْمَ ٱلْوُرُودِ', 'allahumma irzuqni shafa`ata alhusayni yawma alwurudi', ''),
  ('ziyarat-ashura', 137, 'وَثَبِّتْ لِي قَدَمَ صِدْقٍ عِنْدَكَ', 'wa thabbit li qadama sidqin `indaka', ''),
  ('ziyarat-ashura', 138, 'مَعَ ٱلْحُسَيْنِ وَأَصْحَابِ ٱلْحُسَيْنِ', 'ma`a alhusayni wa ashabi alhusayni', ''),
  ('ziyarat-ashura', 139, 'ٱلَّذينَ بَذَلُوٱ مُهَجَهُمْ دُونَ ٱلْحُسَيْنِ عَلَيْهِ ٱلسَّلاَمُ', 'alladhina badhalu muhajahum duna alhusayni', ''),
  ('ziyarat-ashura', 140, '', '', 'Gebet nach der Ziyarat'),
  ('ziyarat-ashura', 141, '', '', 'Danach kann ein Gebet mit zwei Rakʿah verrichtet werden. Nach dem Abschluss kann das folgende Dua gelesen werden:');

commit;

notify pgrst, 'reload schema';

