alter table public.trip_participants
add column assignment_family_id int8
references public.account_families (id) on delete set null;

alter table public.trip_buses
add column leader_participant_id int8;

alter table public.trip_buses
add constraint trip_buses_leader_matches_trip
foreign key (leader_participant_id, trip_id)
references public.trip_participants (id, trip_id)
on delete set null (leader_participant_id);

create index trip_participants_assignment_family_idx
on public.trip_participants (trip_id, assignment_family_id, bus_id)
where assignment_family_id is not null;

create unique index trip_buses_leader_once_per_trip_idx
on public.trip_buses (trip_id, leader_participant_id)
where leader_participant_id is not null;

comment on column public.trip_participants.participant_code is
  'Legacy/internal stable key. It is generated by the current admin workflow and is not shown or entered in the UI.';
comment on column public.trip_participants.assignment_family_id is
  'Optional snapshot marker indicating that this account was assigned through an account family.';
comment on column public.trip_buses.leader_participant_id is
  'Registered person designated as leader of this bus.';

create or replace function public.ensure_trip_profile_bus_assignment(
  p_trip_id int8,
  p_bus_id int8,
  p_profile_id int8,
  p_assignment_family_id int8
)
returns public.trip_participants
language plpgsql
set search_path = ''
as $$
declare
  generated_code text;
  profile_name text;
  saved_assignment public.trip_participants;
begin
  select profiles.display_name
  into profile_name
  from public.profiles as profiles
  where profiles.id = p_profile_id;

  if profile_name is null then
    raise exception 'Profile not found.' using errcode = 'P0002';
  end if;

  select participants.*
  into saved_assignment
  from public.trip_participants as participants
  where participants.trip_id = p_trip_id
    and participants.profile_id = p_profile_id
  order by participants.updated_at desc, participants.id desc
  limit 1
  for update;

  if saved_assignment.id is null then
    generated_code := upper(
      'U' || left(md5(p_trip_id::text || ':' || p_profile_id::text), 19)
    );

    insert into public.trip_participants (
      trip_id,
      bus_id,
      profile_id,
      assignment_family_id,
      participant_code,
      display_name
    )
    values (
      p_trip_id,
      p_bus_id,
      p_profile_id,
      p_assignment_family_id,
      generated_code,
      profile_name
    )
    returning * into saved_assignment;
  else
    update public.trip_participants as participants
    set
      assignment_family_id = p_assignment_family_id,
      bus_id = p_bus_id,
      display_name = profile_name
    where participants.id = saved_assignment.id
    returning participants.* into saved_assignment;
  end if;

  return saved_assignment;
end;
$$;

revoke all on function public.ensure_trip_profile_bus_assignment(int8, int8, int8, int8)
from public, anon, authenticated;

create or replace function public.admin_assign_trip_person(
  p_trip_id int8,
  p_bus_id int8,
  p_user_id uuid
)
returns public.trip_participants
language plpgsql
security definer
set search_path = ''
as $$
declare
  linked_profile_id int8;
  saved_assignment public.trip_participants;
begin
  if (select auth.uid()) is null or not (select public.is_admin()) then
    raise exception 'Admin access required.' using errcode = '42501';
  end if;

  perform pg_advisory_xact_lock(2026090600);

  if not exists (
    select 1
    from public.trips as trips
    where trips.id = p_trip_id
      and trips.archived_at is null
  ) then
    raise exception 'Active trip not found.' using errcode = 'P0002';
  end if;

  if not exists (
    select 1
    from public.trip_buses as buses
    where buses.id = p_bus_id
      and buses.trip_id = p_trip_id
  ) then
    raise exception 'Bus does not belong to the active trip.' using errcode = '23503';
  end if;

  if exists (
    select 1
    from public.bus_boardings as boardings
    where boardings.trip_id = p_trip_id
      and boardings.closed_at is null
  ) then
    raise exception 'Close the active boarding before changing bus assignments.'
      using errcode = '55000';
  end if;

  select profiles.id
  into linked_profile_id
  from public.profiles as profiles
  where profiles.user_id = p_user_id;

  if linked_profile_id is null then
    raise exception 'Profile not found.' using errcode = 'P0002';
  end if;

  if exists (
    select 1
    from public.trip_participants as participants
    where participants.trip_id = p_trip_id
      and participants.profile_id = linked_profile_id
      and participants.assignment_family_id is not null
  ) then
    raise exception 'This person is already assigned through a family.'
      using errcode = '55000';
  end if;

  select *
  into saved_assignment
  from public.ensure_trip_profile_bus_assignment(
    p_trip_id,
    p_bus_id,
    linked_profile_id,
    null
  );

  return saved_assignment;
end;
$$;

create or replace function public.admin_assign_trip_family(
  p_trip_id int8,
  p_bus_id int8,
  p_family_id int8
)
returns setof public.trip_participants
language plpgsql
security definer
set search_path = ''
as $$
declare
  family_profile record;
  saved_assignment public.trip_participants;
  saved_assignment_ids int8[] := '{}'::int8[];
begin
  if (select auth.uid()) is null or not (select public.is_admin()) then
    raise exception 'Admin access required.' using errcode = '42501';
  end if;

  perform pg_advisory_xact_lock(2026090600);

  if not exists (
    select 1
    from public.trips as trips
    where trips.id = p_trip_id
      and trips.archived_at is null
  ) then
    raise exception 'Active trip not found.' using errcode = 'P0002';
  end if;

  if not exists (
    select 1
    from public.trip_buses as buses
    where buses.id = p_bus_id
      and buses.trip_id = p_trip_id
  ) then
    raise exception 'Bus does not belong to the active trip.' using errcode = '23503';
  end if;

  if not exists (
    select 1
    from public.account_families as families
    where families.id = p_family_id
  ) then
    raise exception 'Account family not found.' using errcode = 'P0002';
  end if;

  if not exists (
    select 1
    from public.profiles as profiles
    where profiles.family_id = p_family_id
  ) then
    raise exception 'The selected family has no accounts.' using errcode = '22023';
  end if;

  if exists (
    select 1
    from public.bus_boardings as boardings
    where boardings.trip_id = p_trip_id
      and boardings.closed_at is null
  ) then
    raise exception 'Close the active boarding before changing bus assignments.'
      using errcode = '55000';
  end if;

  if exists (
    select 1
    from public.trip_buses as buses
    join public.trip_participants as leaders
      on leaders.id = buses.leader_participant_id
    join public.profiles as profiles
      on profiles.id = leaders.profile_id
    where buses.trip_id = p_trip_id
      and buses.id <> p_bus_id
      and profiles.family_id = p_family_id
  ) then
    raise exception 'A family member leads another bus.' using errcode = '55000';
  end if;

  for family_profile in
    select profiles.id
    from public.profiles as profiles
    where profiles.family_id = p_family_id
    order by profiles.id
    for update
  loop
    select *
    into saved_assignment
    from public.ensure_trip_profile_bus_assignment(
      p_trip_id,
      p_bus_id,
      family_profile.id,
      p_family_id
    );
    saved_assignment_ids := array_append(saved_assignment_ids, saved_assignment.id);
  end loop;

  return query
  select participants.*
  from public.trip_participants as participants
  where participants.id = any(saved_assignment_ids)
  order by participants.display_name, participants.id;
end;
$$;

create or replace function public.admin_create_trip_bus_with_leader(
  p_trip_id int8,
  p_name text,
  p_leader_user_id uuid
)
returns public.trip_buses
language plpgsql
security definer
set search_path = ''
as $$
declare
  created_bus public.trip_buses;
  existing_family_id int8;
  leader_assignment public.trip_participants;
  leader_profile_id int8;
begin
  if (select auth.uid()) is null or not (select public.is_admin()) then
    raise exception 'Admin access required.' using errcode = '42501';
  end if;

  perform pg_advisory_xact_lock(2026090600);

  if not exists (
    select 1
    from public.trips as trips
    where trips.id = p_trip_id
      and trips.archived_at is null
  ) then
    raise exception 'Active trip not found.' using errcode = 'P0002';
  end if;

  if exists (
    select 1
    from public.bus_boardings as boardings
    where boardings.trip_id = p_trip_id
      and boardings.closed_at is null
  ) then
    raise exception 'Close the active boarding before adding a bus.'
      using errcode = '55000';
  end if;

  select profiles.id
  into leader_profile_id
  from public.profiles as profiles
  where profiles.user_id = p_leader_user_id;

  if leader_profile_id is null then
    raise exception 'Profile not found.' using errcode = 'P0002';
  end if;

  if exists (
    select 1
    from public.trip_buses as buses
    join public.trip_participants as participants
      on participants.id = buses.leader_participant_id
    where buses.trip_id = p_trip_id
      and participants.profile_id = leader_profile_id
  ) then
    raise exception 'This person already leads another bus.' using errcode = '23505';
  end if;

  select participants.assignment_family_id
  into existing_family_id
  from public.trip_participants as participants
  where participants.trip_id = p_trip_id
    and participants.profile_id = leader_profile_id
  order by participants.updated_at desc, participants.id desc
  limit 1;

  if existing_family_id is not null then
    raise exception 'A person assigned through a family cannot be moved to a new bus alone.'
      using errcode = '55000';
  end if;

  insert into public.trip_buses (trip_id, name, sort_order)
  values (
    p_trip_id,
    btrim(p_name),
    coalesce(
      (select max(buses.sort_order) + 1 from public.trip_buses as buses where buses.trip_id = p_trip_id),
      0
    )
  )
  returning * into created_bus;

  select *
  into leader_assignment
  from public.ensure_trip_profile_bus_assignment(
    p_trip_id,
    created_bus.id,
    leader_profile_id,
    null
  );

  update public.trip_buses as buses
  set leader_participant_id = leader_assignment.id
  where buses.id = created_bus.id
  returning buses.* into created_bus;

  return created_bus;
end;
$$;

create or replace function public.admin_set_trip_bus_leader(
  p_bus_id int8,
  p_leader_user_id uuid
)
returns public.trip_buses
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_family_id int8;
  leader_assignment public.trip_participants;
  leader_profile_id int8;
  saved_bus public.trip_buses;
begin
  if (select auth.uid()) is null or not (select public.is_admin()) then
    raise exception 'Admin access required.' using errcode = '42501';
  end if;

  perform pg_advisory_xact_lock(2026090600);

  select buses.*
  into saved_bus
  from public.trip_buses as buses
  join public.trips as trips on trips.id = buses.trip_id
  where buses.id = p_bus_id
    and trips.archived_at is null
  for update of buses;

  if saved_bus.id is null then
    raise exception 'Bus in active trip not found.' using errcode = 'P0002';
  end if;

  if exists (
    select 1
    from public.bus_boardings as boardings
    where boardings.trip_id = saved_bus.trip_id
      and boardings.closed_at is null
  ) then
    raise exception 'Close the active boarding before changing the bus leader.'
      using errcode = '55000';
  end if;

  select profiles.id
  into leader_profile_id
  from public.profiles as profiles
  where profiles.user_id = p_leader_user_id;

  if leader_profile_id is null then
    raise exception 'Profile not found.' using errcode = 'P0002';
  end if;

  if exists (
    select 1
    from public.trip_buses as buses
    join public.trip_participants as participants
      on participants.id = buses.leader_participant_id
    where buses.trip_id = saved_bus.trip_id
      and buses.id <> saved_bus.id
      and participants.profile_id = leader_profile_id
  ) then
    raise exception 'This person already leads another bus.' using errcode = '23505';
  end if;

  select participants.assignment_family_id
  into current_family_id
  from public.trip_participants as participants
  where participants.trip_id = saved_bus.trip_id
    and participants.profile_id = leader_profile_id
  order by participants.updated_at desc, participants.id desc
  limit 1;

  if current_family_id is not null and exists (
    select 1
    from public.trip_participants as participants
    where participants.trip_id = saved_bus.trip_id
      and participants.profile_id = leader_profile_id
      and participants.assignment_family_id = current_family_id
      and participants.bus_id <> saved_bus.id
  ) then
    raise exception 'A person assigned through a family cannot lead another bus.'
      using errcode = '55000';
  end if;

  select *
  into leader_assignment
  from public.ensure_trip_profile_bus_assignment(
    saved_bus.trip_id,
    saved_bus.id,
    leader_profile_id,
    current_family_id
  );

  update public.trip_buses as buses
  set leader_participant_id = leader_assignment.id
  where buses.id = saved_bus.id
  returning buses.* into saved_bus;

  return saved_bus;
end;
$$;

create or replace function public.admin_copy_trip_bus_setup(
  p_source_trip_id int8,
  p_name text
)
returns public.trips
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor_profile_id int8;
  copied_family_id int8;
  created_trip public.trips;
  leader_assignment public.trip_participants;
  leader_profile_id int8;
  saved_assignment public.trip_participants;
  source_assignment record;
  source_bus record;
  source_bus_ids int8[] := '{}'::int8[];
  target_bus_id int8;
  target_bus_ids int8[] := '{}'::int8[];
begin
  if (select auth.uid()) is null or not (select public.is_admin()) then
    raise exception 'Admin access required.' using errcode = '42501';
  end if;

  perform pg_advisory_xact_lock(2026090600);

  if not exists (
    select 1
    from public.trips as trips
    where trips.id = p_source_trip_id
      and trips.archived_at is not null
  ) then
    raise exception 'Closed source trip not found.' using errcode = 'P0002';
  end if;

  select profiles.id
  into actor_profile_id
  from public.profiles as profiles
  where profiles.user_id = (select auth.uid());

  insert into public.trips (name, created_by_profile_id)
  values (btrim(p_name), actor_profile_id)
  returning * into created_trip;

  for source_bus in
    select buses.*
    from public.trip_buses as buses
    where buses.trip_id = p_source_trip_id
    order by buses.sort_order, buses.id
  loop
    insert into public.trip_buses (trip_id, name, sort_order)
    values (created_trip.id, source_bus.name, source_bus.sort_order)
    returning id into target_bus_id;

    source_bus_ids := array_append(source_bus_ids, source_bus.id);
    target_bus_ids := array_append(target_bus_ids, target_bus_id);
  end loop;

  for source_assignment in
    select distinct on (participants.profile_id)
      participants.assignment_family_id,
      participants.bus_id,
      participants.profile_id
    from public.trip_participants as participants
    where participants.trip_id = p_source_trip_id
      and participants.profile_id is not null
      and participants.bus_id is not null
    order by
      participants.profile_id,
      participants.updated_at desc,
      participants.id desc
  loop
    target_bus_id := target_bus_ids[array_position(source_bus_ids, source_assignment.bus_id)];
    if target_bus_id is null then
      continue;
    end if;

    select case
      when profiles.family_id = source_assignment.assignment_family_id
        then source_assignment.assignment_family_id
      else null
    end
    into copied_family_id
    from public.profiles as profiles
    where profiles.id = source_assignment.profile_id;

    select *
    into saved_assignment
    from public.ensure_trip_profile_bus_assignment(
      created_trip.id,
      target_bus_id,
      source_assignment.profile_id,
      copied_family_id
    );
  end loop;

  for source_bus in
    select buses.*
    from public.trip_buses as buses
    where buses.trip_id = p_source_trip_id
      and buses.leader_participant_id is not null
    order by buses.sort_order, buses.id
  loop
    select participants.profile_id
    into leader_profile_id
    from public.trip_participants as participants
    where participants.id = source_bus.leader_participant_id;

    if leader_profile_id is null then
      continue;
    end if;

    target_bus_id := target_bus_ids[array_position(source_bus_ids, source_bus.id)];

    select participants.assignment_family_id
    into copied_family_id
    from public.trip_participants as participants
    where participants.trip_id = created_trip.id
      and participants.profile_id = leader_profile_id
    order by participants.updated_at desc, participants.id desc
    limit 1;

    select *
    into leader_assignment
    from public.ensure_trip_profile_bus_assignment(
      created_trip.id,
      target_bus_id,
      leader_profile_id,
      copied_family_id
    );

    update public.trip_buses as buses
    set leader_participant_id = leader_assignment.id
    where buses.id = target_bus_id;
  end loop;

  return created_trip;
exception
  when unique_violation then
    raise exception 'An active trip already exists or the trip name is invalid.'
      using errcode = '23505';
end;
$$;

create or replace function public.claim_due_general_alarm_notifications()
returns table (
  attempt_id int8,
  expo_push_token text,
  locale text,
  platform text,
  boarding_id int8,
  participant_id int8,
  participant_code text,
  expected_status public.bus_boarding_status,
  is_urgent boolean,
  title text,
  departure_at timestamptz
)
language sql
security definer
set search_path = ''
as $$
  with due as (
    select
      boardings.id as boarding_id,
      participants.id as participant_id,
      participants.display_name as participant_code,
      devices.id as push_device_id,
      devices.expo_push_token,
      devices.locale,
      devices.platform,
      case
        when responses.id is null then 'read'::public.bus_boarding_status
        when responses.status = 'read'::public.bus_boarding_status
          then 'on_way'::public.bus_boarding_status
        else 'boarded'::public.bus_boarding_status
      end as expected_status,
      floor(
        extract(
          epoch from (
            now() - coalesce(responses.updated_at, boardings.opened_at)
          )
        ) / (boardings.reminder_interval_minutes * 60)
      )::int4 as reminder_slot,
      boardings.departure_at <= now()
        + make_interval(mins => boardings.urgent_before_minutes) as is_urgent,
      boardings.title,
      boardings.departure_at
    from public.bus_boardings as boardings
    join public.trip_participants as participants
      on participants.trip_id = boardings.trip_id
    join public.push_notification_devices as devices
      on devices.profile_id = participants.profile_id
    left join public.bus_boarding_responses as responses
      on responses.boarding_id = boardings.id
      and responses.participant_id = participants.id
    where boardings.closed_at is null
      and (
        responses.id is null
        or responses.status in (
          'read'::public.bus_boarding_status,
          'on_way'::public.bus_boarding_status
        )
      )
      and (
        responses.id is null
        or responses.updated_at
          + make_interval(mins => boardings.reminder_interval_minutes) <= now()
      )
  ),
  claimed as (
    insert into public.general_alarm_notification_attempts (
      boarding_id,
      participant_id,
      push_device_id,
      expected_status,
      reminder_slot
    )
    select
      due.boarding_id,
      due.participant_id,
      due.push_device_id,
      due.expected_status,
      due.reminder_slot
    from due
    where due.reminder_slot >= 0
    on conflict do nothing
    returning
      id,
      general_alarm_notification_attempts.boarding_id,
      general_alarm_notification_attempts.participant_id,
      general_alarm_notification_attempts.push_device_id,
      general_alarm_notification_attempts.expected_status,
      general_alarm_notification_attempts.reminder_slot
  )
  select
    claimed.id,
    due.expo_push_token,
    due.locale,
    due.platform,
    due.boarding_id,
    due.participant_id,
    due.participant_code,
    due.expected_status,
    due.is_urgent,
    due.title,
    due.departure_at
  from claimed
  join due
    on due.boarding_id = claimed.boarding_id
    and due.participant_id = claimed.participant_id
    and due.push_device_id = claimed.push_device_id
    and due.expected_status = claimed.expected_status
    and due.reminder_slot = claimed.reminder_slot;
$$;

comment on function public.claim_due_general_alarm_notifications() is
  'Claims due notifications and returns participant display names in the legacy participant_code response field.';

revoke all on function public.admin_assign_trip_person(int8, int8, uuid)
from public, anon;
revoke all on function public.admin_assign_trip_family(int8, int8, int8)
from public, anon;
revoke all on function public.admin_create_trip_bus_with_leader(int8, text, uuid)
from public, anon;
revoke all on function public.admin_set_trip_bus_leader(int8, uuid)
from public, anon;
revoke all on function public.admin_copy_trip_bus_setup(int8, text)
from public, anon;

grant execute on function public.admin_assign_trip_person(int8, int8, uuid)
to authenticated;
grant execute on function public.admin_assign_trip_family(int8, int8, int8)
to authenticated;
grant execute on function public.admin_create_trip_bus_with_leader(int8, text, uuid)
to authenticated;
grant execute on function public.admin_set_trip_bus_leader(int8, uuid)
to authenticated;
grant execute on function public.admin_copy_trip_bus_setup(int8, text)
to authenticated;

notify pgrst, 'reload schema';
